#!/usr/bin/env node
'use strict';

// Deterministic Android vectors from the same editable master as the Flutter kit.
// --raster additionally uses an already installed Playwright/Chromium for legacy PNGs.
const fs = require('node:fs');
const path = require('node:path');
const scenes = require('../docs/branding/fox-kit/scenes.js');
const root = path.resolve(__dirname, '..');
const res = path.join(root, 'android/app/src/main/res');

function masterPaths() {
  const source = scenes.fox();
  const paths = [...source.matchAll(/<path fill="currentColor" d="([^"]+)"\/>/g)].map((match) => match[1]);
  const eye = source.match(/<circle cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)"/);
  if (paths.length !== 2 || !eye) throw new Error('Fox master changed: review Android layer extraction.');
  const [, rawX, rawY, rawR] = eye;
  const x = Number(rawX), y = Number(rawY), r = Number(rawR);
  // An actual cutout keeps the eye transparent in themed/notification silhouettes.
  const hole = `M${x - r},${y}a${r},${r} 0 1,0 ${r * 2},0a${r},${r} 0 1,0 ${-r * 2},0Z`;
  return { tail: paths[0], body: paths[1] + hole };
}

function vector({ color, size, scale = 1, dx = 0, dy = 0 }) {
  const { tail, body } = masterPaths();
  return `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_afterword_platform_icons.cjs. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="${size}dp" android:height="${size}dp"
    android:viewportWidth="160" android:viewportHeight="160">
    <group android:scaleX="${scale}" android:scaleY="${scale}"
        android:translateX="${dx}" android:translateY="${dy}">
        <path android:fillColor="${color}" android:pathData="${tail}" />
        <path android:fillColor="${color}" android:fillType="evenOdd" android:pathData="${body}" />
    </group>
</vector>
`;
}

function outputs() {
  const adaptive = (monochrome) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/generate_afterword_platform_icons.cjs. -->
<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
    <background android:drawable="@color/afterword_green" />
    <foreground android:drawable="@drawable/ic_afterword_foreground" />
${monochrome ? '    <monochrome android:drawable="@drawable/ic_afterword_monochrome" />\n' : ''}</adaptive-icon>
`;
  return {
    'values/afterword_colors.xml': '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n    <color name="afterword_green">#476B4F</color>\n    <color name="afterword_paper">#FAF8F3</color>\n</resources>\n',
    'drawable/ic_afterword_foreground.xml': vector({ color: '@color/afterword_paper', size: 108, scale: .7, dx: 21.9, dy: 24 }),
    'drawable/ic_afterword_monochrome.xml': vector({ color: '#FFFFFFFF', size: 108, scale: .7, dx: 21.9, dy: 24 }),
    'drawable/ic_afterword_notification.xml': vector({ color: '#FFFFFFFF', size: 24, scale: 1.15, dx: -14.3, dy: -12 }),
    'drawable/ic_afterword_splash.xml': vector({ color: '@color/afterword_green', size: 160, scale: .76, dx: 16.92, dy: 19.2 }),
    'mipmap-anydpi-v26/ic_launcher.xml': adaptive(false),
    'mipmap-anydpi-v33/ic_launcher.xml': adaptive(true),
  };
}

async function main() {
  const check = process.argv.includes('--check');
  for (const [relative, content] of Object.entries(outputs())) {
    const file = path.join(res, relative);
    if (check) {
      if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) throw new Error('Stale Android vector: ' + relative);
    } else {
      fs.mkdirSync(path.dirname(file), { recursive: true });
      fs.writeFileSync(file, content);
    }
  }
  if (process.argv.includes('--raster')) {
    if (check) throw new Error('Use --check and --raster separately.');
    const { chromium } = require('playwright');
    const browser = await chromium.launch({ headless: true, ...(process.env.BROWSER_EXECUTABLE ? { executablePath: process.env.BROWSER_EXECUTABLE } : {}) });
    try {
      const page = await browser.newPage({ deviceScaleFactor: 1 });
      for (const [density, size] of Object.entries({ mdpi: 48, hdpi: 72, xhdpi: 96, xxhdpi: 144, xxxhdpi: 192 })) {
        await page.setViewportSize({ width: size, height: size });
        await page.setContent('<style>html,body{margin:0;width:100%;height:100%;background:#476b4f}svg{display:block}</style>' + scenes.fox({ size, color: '#faf8f3', background: '#476b4f', rounded: false }));
        await page.screenshot({ path: path.join(res, `mipmap-${density}/ic_launcher.png`) });
      }
    } finally { await browser.close(); }
  }
  console.log(check ? 'Android vector resources match the master.' : 'Android fox resources generated.');
}

module.exports = { masterPaths, vector, outputs };
if (require.main === module) main().catch((error) => { console.error(error); process.exitCode = 1; });
